# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5f611da15d0f0ed7f7ec8efa481a481a88bf06078ba76e389825ba3d677369d2a4b909568396fad1b0d97e9b2eaad2342d31074a7e375ec5cfe87abd301780

test:
  secret_key_base: 491ed633047faec2beef070b04d8fa13e14ad40979f3cd12ef4b9dc70de6f5eb648ad091c673eaac8a02f2133542448848c6d571cb8845f9b10d6ec6d151dc21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
